## EXPERIMENT #2: Numerical Python (Numpy)
--------------------------------------------------------
## Name: Kyle Adrienne S. Hizon
## Section: 2ECEA
--------------------------------------------------------

## PROBLEM 1: NORMALIZATION PROBLEM

In [6]:
import numpy as np

# Creating a 5x5 array matrix inside a variable X with random numbers
X = np.random.random((5,5))

# Creating a Normalization function that normalizes an array based on their mean and standard deviation in the formula of: (array - mean)/(std)
def Normalization(matrix):
    normal = (matrix - np.mean(X))/np.std(X)
    return normal
    
# Saving the value of the Normalization function as npy
np.save("X_normalized.npy",Normalization(X))

# Putting the loaded npy file inside the norm_matrix variable
norm_matrix = np.load("X_normalized.npy")

# Rounding off the standard deviation into 4 decimal places
rounded_std = round(np.std(X),4)

# Printing the informations: This will print the 5x5 matrix itself, the mean, the standard deviation, and the loaded npy file called "normalized_matrix.npy"
print("The matrix is \n\n",X,"\n\nThe mean for overall matrix is",np.mean(X),"\nThe standard deviation for the matrix is",rounded_std,"\nTherefore, the normalized matrix is\n\n",norm_matrix)

The matrix is 

 [[0.83230569 0.79958645 0.0746514  0.18941334 0.7245609 ]
 [0.34263309 0.71632171 0.8349197  0.24166599 0.70690369]
 [0.96183242 0.42184955 0.35336434 0.51064733 0.37549162]
 [0.8901211  0.58327154 0.78981703 0.57251595 0.86803533]
 [0.30121002 0.59548106 0.03786735 0.1984996  0.04520951]] 

The mean for overall matrix is 0.5187270280167652 
The standard deviation for the matrix is 0.2837 
Therefore, the normalized matrix is

 [[ 1.1051416   0.98982955 -1.56505051 -1.16059637  0.72541789]
 [-0.62060581  0.69638061  1.11435412 -0.97644295  0.6631888 ]
 [ 1.56163114 -0.34142417 -0.58278577 -0.0284752  -0.50480287]
 [ 1.30889976  0.22747348  0.95539931  0.18956768  1.23106314]
 [-0.76659265  0.27050334 -1.69468812 -1.12857376 -1.66881224]]


## PROBLEM 2: DIVISIBLE BY 3 PROBLEM

In [8]:
import numpy as np

# Create a matrix ranging from 1-100 that are squared
matrix = np.arange(1,101,1)**2

# Reshape the matrix into 10x10
matrix = matrix.reshape(10,10)

# Create a function that will get the all indices of the matrix that are divisible by 3
def divisibility_by_3(array):
    array = array[array%3 == 0]
    return array

# Saving the value of the divisibility_by_3 function as np
np.save("div_by_3.npy",divisibility_by_3(matrix))

# Putting the loaded npy file inside the div3_matrix variable
div3_matrix = np.load("div_by_3.npy")

# Printing the information: This will print the 10x10 matrix itself and the list of numbers that are divisible by 3
print("The 10x10 matrix with all squared values from 1-100 is\n\n",matrix,"\n\nThe following numbers that are divisible by 3 are\n\n",div3_matrix)

The 10x10 matrix with all squared values from 1-100 is

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

The following numbers that are divisible by 3 are

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
